schema_version: 1

context:
  version: "1.0.2"
  python_min: "3.11"

package:
  name: ome-zarrpari
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/ome-zarrpari/ome_zarrpari-${{ version }}.tar.gz
  sha256: ce0230758e9fc3425a91db744a997fbe3f44b8840327cfe9ed83a17c7617c6d5

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42.0.0
    - setuptools-scm
    - pip
  run:
    - python
    - napari
    - qtpy
    - pydantic-zarr >=0.9.2
    - ome-zarr-models >=1.0
    - zarr
    - requests
    - aiohttp
    - gcsfs

tests:
  - script:
      - python -c "from ome_zarrpari import __version__;print(__version__)"
      - pip check
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pyqt

about:
  summary: A plugin to load and use OME-Zarr data
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/ome-zarrpari/
  documentation: https://ome-zarrpari.readthedocs.io

extra:
  recipe-maintainers:
    - dstansby
